name: build-mac
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        brew install fftw ncurses libtool automake portaudio iniparser
        ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
    - name: Generate configure
      run: ./autogen.sh
    - name: Run ./configure
      run: LDFLAGS="-L/usr/local/opt/ncurses/lib" CPPFLAGS="-I/usr/local/opt/ncurses/include" ./configure
    - name: Run make
      run: make
